# Generated by Django 2.0.2 on 2020-02-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stackapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('pagesize', models.IntegerField()),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('min', models.DateField()),
                ('max', models.DateField()),
                ('sort', models.CharField(max_length=999)),
                ('order', models.CharField(max_length=999)),
                ('q', models.CharField(max_length=999)),
                ('accepted', models.CharField(max_length=999)),
                ('answers', models.IntegerField()),
                ('body', models.CharField(max_length=999)),
                ('closed', models.CharField(max_length=999)),
                ('migrated', models.CharField(max_length=999)),
                ('notice', models.CharField(max_length=999)),
                ('nottagged', models.CharField(max_length=999)),
                ('tagged', models.CharField(max_length=999)),
                ('title', models.CharField(max_length=999)),
                ('user', models.IntegerField()),
                ('url', models.CharField(max_length=999)),
                ('views', models.IntegerField()),
                ('wiki', models.CharField(max_length=999)),
            ],
        ),
    ]
